import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { fresh, draw, standings, thirds, summary, winner, played, setResult, demo, validateTournament, reconcile, type Tournament, type Team, type Match, type Result } from './engine';
import './style.css';
import { apiFetch, embedded, draftKey, host } from './transport';
if (embedded) document.documentElement.classList.add('embedded', `host-${host}`);
const tabs=['Takımlar','Gruplar','Grup Maçları','3. Ler Turnuvası','Finaller','Turnuva Özeti'] as const;
type Tab=typeof tabs[number];
type Saved={id:string;name:string;updated:string};
const labels={points:'Puan',hits:'Vurulan oyuncu',flags:'Bayrak',sweeps:'Tam eleme'};
function App(){
 const [t,setT]=useState<Tournament>(()=>{try{const raw=localStorage.getItem(draftKey);if(raw){const x=JSON.parse(raw);validateTournament(x);return reconcile(x).tournament;}}catch{}return fresh();});
 const [tab,setTab]=useState<Tab>('Takımlar'); const [saved,setSaved]=useState<Saved[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);
 const [editor,setEditor]=useState<Team|null>(null);const [match,setMatch]=useState<Match|null>(null);const [group,setGroup]=useState('all');const [query,setQuery]=useState('');const [seed,setSeed]=useState(t.seed);
 const name=(id:string|null)=>t.teams.find(x=>x.id===id)?.name??'Katılımcı bekleniyor';
 const change=(next:Tournament)=>{setT(next);setDirty(true);setMessage('Değişiklikler taslağa alındı. Kalıcı kayıt için Kaydet’i kullanın.');};
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify(t));}catch{setMessage('Tarayıcı taslağı kaydedilemedi. Sunucuya kaydedin veya dışa aktarın.');}},[t]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 const refresh=async()=>{const res=await apiFetch('/api/tournaments');if(!res.ok)throw new Error('Kayıt listesi alınamadı.');setSaved(await res.json());};
 useEffect(()=>{refresh().catch(()=>setMessage('Sunucuya ulaşılamıyor. Yerel taslak kullanılabilir; kalıcı kayıt için sunucuyu başlatın.'));},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'İşlem başarısız.');}finally{setBusy(false);}};
 const abandon=()=>!dirty||confirm('Kaydedilmemiş değişiklikler var. Devam edilsin mi?');
 const save=()=>run(async()=>{const res=await apiFetch(`/api/tournaments/${encodeURIComponent(t.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(t)});const data=await res.json();if(!res.ok)throw new Error(data.error);setT(data);setDirty(false);await refresh();setMessage('Turnuva kalıcı kayda yazıldı.');});
 const open=(id:string)=>run(async()=>{if(!id||!abandon())return;const res=await apiFetch(`/api/tournaments/${encodeURIComponent(id)}`);if(!res.ok)throw new Error('Turnuva açılamadı.');const data=await res.json();validateTournament(data);setT(reconcile(data).tournament);setSeed(data.seed);setDirty(false);setMessage('Kaydedilen turnuva açıldı.');});
 const exportFile=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(t,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='turnuva.json';a.click();URL.revokeObjectURL(url);};
 const importFile=(file?:File)=>run(async()=>{if(!file||!abandon())return;const x=JSON.parse(await file.text());validateTournament(x);x.id=crypto.randomUUID();x.revision=0;const result=reconcile(x);change(result.tournament);setSeed(x.seed);setMessage(`Dosya yeni turnuva olarak açıldı.${result.invalidated.length?' Geçersiz eşleşme sonuçları temizlendi.':''}`);});
 const doDraw=()=>{try{const next=draw(t,seed);const changes=JSON.stringify(next.groups)!==JSON.stringify(t.groups);if(changes&&t.matches.some(m=>Object.values(m.result).some(v=>v!==null))&&!confirm('Yeni kura bütün maç sonuçlarını sıfırlayacak. Devam edilsin mi?'))return;change(next);setTab('Gruplar');}catch(e){setMessage((e as Error).message);}};
 const saveTeam=(team:Team)=>{try{const next=structuredClone(t);const idx=next.teams.findIndex(x=>x.id===team.id);if(idx>=0)next.teams[idx]=team;else{if(next.teams.length>=40)throw new Error('En fazla 40 takım kaydedilebilir.');next.teams.push(team);}validateTournament(next);change(next);setEditor(null);}catch(e){setMessage((e as Error).message);}};
 const removeTeam=(id:string)=>{if(!confirm(t.groups.length?'Takımı silmek kurayı ve tüm sonuçları sıfırlayacak. Devam edilsin mi?':'Takım silinsin mi?'))return;const next=structuredClone(t);next.teams=next.teams.filter(x=>x.id!==id);next.groups=[];next.matches=[];next.log.push('Takım silindi; kura ve sonuçlar sıfırlandı.');change(next);};
 const saveMatch=(r:Result)=>{try{const next=setResult(t,match!.id,r);if(next.invalidated.length&&!confirm(`Bu düzeltme ${next.invalidated.length} sonraki maçın eşleşmesini değiştirecek ve sonuçlarını temizleyecek. Devam edilsin mi?`))return;next.tournament.log.push(`${match!.round} / ${match!.id}: sonuç güncellendi.`);change(next.tournament);setMatch(null);if(next.invalidated.length)setMessage(`${next.invalidated.length} geçersiz sonuç temizlendi. Ayrıntılar kayıt geçmişinde.`);}catch(e){setMessage((e as Error).message);}};
 const ss=standings(t),ts=thirds(t),sum=summary(t);const done=t.matches.filter(m=>m.stage==='group'?played(m):!!winner(m)).length;
 const matchView=(ms:Match[])=>ms.map(m=><div className="match-row" key={m.id}><div className="match-meta"><span>{m.id}</span><small>{m.round}</small></div><div className="versus"><span>{name(m.home)}</span><strong>{m.result.a??'—'} <i>:</i> {m.result.b??'—'}</strong><span>{name(m.away)}</span></div><div className="result-state">{winner(m)?'Tamamlandı':m.stage==='group'&&played(m)?'Tamamlandı':played(m)?'Kazanan seçilmeli':'Bekliyor'}{m.result.flag&&<small>Bayrak: {name(m.result.flag)}</small>}{m.result.sweep&&<small>Tam eleme: {name(m.result.sweep)}</small>}</div><button disabled={!m.home||!m.away} onClick={()=>setMatch(m)}>Sonuç gir / düzelt</button></div>);
 return <fieldset disabled={busy} className="busy-scope"><aside><div className="brand"><span className="brand-mark">T</span><div>Turnuva<small>YÖNETİM MASASI</small></div></div><nav>{tabs.map((x,i)=><button className={tab===x?'active':''} key={x} onClick={()=>setTab(x)}><span>0{i+1}</span>{x}</button>)}</nav><div className="side-note">40 takım · 10 grup<br/>60 + 7 + 22 maç<small>{t.demo?'DEMO / TEST VERİSİ':'GERÇEK TURNUVA · BOŞ SONUÇLA BAŞLAR'}</small></div></aside><main><header><div><span className="eyebrow">TURNUVA ÇALIŞMA ALANI</span><input className="title-input" aria-label="Turnuva adı" maxLength={200} value={t.name} onChange={e=>change({...t,name:e.target.value})}/></div><div className="save-area"><span>{dirty?'Kaydedilmemiş değişiklikler':'Kayıt güncel'}</span><button className="primary" onClick={save} disabled={busy||!t.name.trim()}>Kaydet</button></div></header><div className="toolbar"><select aria-label="Kayıtlı turnuvayı aç" value="" disabled={busy} onChange={e=>open(e.target.value)}><option value="">Kayıtlı turnuvayı aç…</option>{saved.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><button onClick={()=>{if(abandon()){change(fresh());setSeed('1');setTab('Takımlar');}}}>Yeni turnuva</button><button onClick={exportFile}>Dışa aktar</button><label className="file-button">Dosyadan aç<input type="file" accept=".json" onChange={e=>{importFile(e.target.files?.[0]);e.target.value='';}}/></label><button onClick={()=>{if(!abandon())return;if(!confirm('Ayrı ve tamamlanmış 89 maçlık demo turnuvası oluşturulsun mu?'))return;change(demo());setSeed('2026');setTab('Turnuva Özeti');}}>Demo/Test verisi oluştur</button></div>{t.demo&&<div className="demo-banner">DEMO / TEST VERİSİ — Takımlar ve skorlar gerçek sonuç değildir.</div>}<div className="notice" role="status">{message||'Takımları ekleyin, kurayı oluşturun ve maç sonuçlarını girin.'}</div><div className="section-head"><div><span className="eyebrow">{t.teams.length} / 40 TAKIM · {done} / {t.matches.length||89} MAÇ TAMAMLANDI</span><h1>{tab}</h1></div>{tab==='Takımlar'&&<button className="primary" disabled={t.teams.length>=40} onClick={()=>setEditor({id:crypto.randomUUID(),name:'',city:'',players:[],captain:''})}>+ Takım ekle</button>}</div>
 {tab==='Takımlar'&&<><input className="search" aria-label="Takım ara" placeholder="Takım veya şehir ara…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>Takım</th><th>Şehir</th><th>Kaptan</th><th>Oyuncu</th><th>İşlem</th></tr></thead><tbody>{t.teams.filter(x=>(x.name+' '+x.city).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).map((team,i)=><tr key={team.id}><td><small>{String(i+1).padStart(2,'0')}</small> {team.name}</td><td>{team.city||'—'}</td><td>{team.captain||'—'}</td><td>{team.players.length}</td><td><button onClick={()=>setEditor(team)}>Düzenle</button><button onClick={()=>removeTeam(team.id)}>Sil</button></td></tr>)}</tbody></table></div>{!t.teams.length&&<div className="empty"><h2>İlk takımı ekleyin</h2><p>Takım adı, şehir, oyuncular ve kaptan bilgilerini girin. Kura için 40 takım gereklidir.</p></div>}</>}
 {tab==='Gruplar'&&<><div className="draw-bar"><label>Kura numarası / seed<input value={seed} maxLength={100} onChange={e=>setSeed(e.target.value)}/></label><button className="primary" onClick={doDraw}>Grup kurasını oluştur</button><p>Aynı takımlar ve aynı seed, aynı kurayı üretir.</p></div><p className="muted">Puan → vurulan oyuncu → bayrak → tam eleme → kura sırası. Puan: galibiyet 3, beraberlik 1, bayrak +5, tam eleme +2.</p><div className="groups">{ss.map((rows,g)=><section key={g}><h2>Grup {String.fromCharCode(65+g)}</h2><table><thead><tr><th>Takım</th><th>O</th><th>P</th><th>V</th><th>B</th><th>TE</th></tr></thead><tbody>{rows.map((s,i)=><tr key={s.id}><td><small>{i+1}</small> {name(s.id)}</td><td>{s.played}</td><td><strong>{s.points}</strong></td><td>{s.hits}</td><td>{s.flags}</td><td>{s.sweeps}</td></tr>)}</tbody></table></section>)}</div>{!ss.length&&<div className="empty">40 takımı ekledikten sonra kura oluşturun.</div>}</>}
 {tab==='Grup Maçları'&&<><div className="filters"><label>Grup filtresi <select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Tüm gruplar</option>{t.groups.map((_,g)=><option key={g} value={g}>Grup {String.fromCharCode(65+g)}</option>)}</select></label><span>İki skor girildiğinde maç tamamlanır; 0–0 geçerli bir sonuçtur.</span></div>{matchView(t.matches.filter(m=>m.stage==='group'&&(group==='all'||m.group===Number(group))))}{!t.matches.length&&<div className="empty">Maç programı için önce grup kurasını oluşturun.</div>}</>}
 {(tab==='3. Ler Turnuvası'||tab==='Finaller')&&<>{tab==='3. Ler Turnuvası'&&<div className="third-list"><h2>Grup üçüncüleri</h2><p>Son ölçütte grup harfi sırası kullanılır. Katılımcılar 60 grup maçı tamamlandığında kesinleşir.</p>{ts.map((s,i)=><div key={s.id}><span>Grup {String.fromCharCode(65+s.group)} · {name(s.id)} · {s.points} puan</span><strong>{i===0?'En iyi · ön eleme':i===9?'En başarısız · elendi':'Üçüncüler turnuvası'}</strong></div>)}</div>}{(tab==='Finaller'?['Ön Eleme','Son 16','Çeyrek Final','Yarı Final','Üçüncülük Maçı','Final']:['Çeyrek Final','Yarı Final','Final']).map(round=><section className="round" key={round}><h2>{round}</h2>{matchView(t.matches.filter(m=>m.stage===(tab==='Finaller'?'finals':'third')&&m.round===round))}</section>)}{!t.matches.length&&<div className="empty">Önce kura oluşturun. Tur katılımcıları sonuçlara göre otomatik aktarılır.</div>}</>}
 {tab==='Turnuva Özeti'&&<><div className="podium">{([['Altın',sum.gold],['Gümüş',sum.silver],['Bronz',sum.bronze]] as const).map(([label,n],i)=><section key={label}><span className="medal">0{i+1}</span><small>{label} madalya</small><h2>{n||'Sonuç bekleniyor'}</h2></section>)}</div><div className="stats">{(['group','finals'] as const).map(stage=><section key={stage}><h2>{stage==='group'?'Grup istatistikleri':'Final istatistikleri'}</h2>{Object.entries(labels).map(([k,label])=><div key={k}><span>En çok {label.toLocaleLowerCase('tr')}</span><strong>{sum[stage][k]||'—'}</strong></div>)}</section>)}</div><details><summary>Kayıt ve düzeltme geçmişi ({t.log.length})</summary>{t.log.map((x,i)=><p key={i}>{x}</p>)}</details></>}
 </main>{editor&&<TeamEditor team={editor} onClose={()=>setEditor(null)} onSave={saveTeam}/ >}{match&&<MatchEditor match={match} name={name} onClose={()=>setMatch(null)} onSave={saveMatch}/>}</fieldset>;
}
function TeamEditor({team,onSave,onClose}:{team:Team;onSave:(t:Team)=>void;onClose:()=>void}){
 const [name,setName]=useState(team.name),[city,setCity]=useState(team.city),[players,setPlayers]=useState(team.players.join('\n')),[captain,setCaptain]=useState(team.captain);
 const list=players.split('\n').map(x=>x.trim()).filter(Boolean);
 return <div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();onSave({...team,name:name.trim(),city:city.trim(),players:list,captain});}}><h2>Takım bilgileri</h2><label>Takım adı<input required autoFocus maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Şehir<input maxLength={100} value={city} onChange={e=>setCity(e.target.value)}/></label><label>Oyuncular <small>Her satıra bir oyuncu</small><textarea rows={6} value={players} onChange={e=>setPlayers(e.target.value)}/></label><label>Kaptan<select aria-label="Kaptan" value={captain} onChange={e=>setCaptain(e.target.value)}><option value="">Kaptan seçilmedi</option>{list.map((p,i)=><option key={i}>{p}</option>)}</select></label><div className="modal-actions"><button type="button" onClick={onClose}>Vazgeç</button><button className="primary">Takımı kaydet</button></div></form></div>;
}
function MatchEditor({match:m,name,onSave,onClose}:{match:Match;name:(id:string|null)=>string;onSave:(r:Result)=>void;onClose:()=>void}){
 const [r,setR]=useState<Result>(structuredClone(m.result));
 const options=<><option value="">Yok / seçilmedi</option><option value={m.home!}>{name(m.home)}</option><option value={m.away!}>{name(m.away)}</option></>;
 return <div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();onSave(r);}}><span className="eyebrow">{m.round} · {m.id}</span><h2>Maç sonucu</h2><div className="score-inputs">{(['a','b'] as const).map((k,i)=><label key={k}>{name(i===0?m.home:m.away)}<input aria-label={i===0?'Ev sahibi skoru':'Deplasman skoru'} type="number" min={0} max={10000} step={1} value={r[k]??''} onChange={e=>setR({...r,[k]:e.target.value===''?null:Number(e.target.value),winner:null})}/></label>)}</div><label>Bayrak alan takım<select aria-label="Bayrak alan takım" value={r.flag??''} onChange={e=>setR({...r,flag:e.target.value||null})}>{options}</select></label><label>Tam eleme yapan takım<select aria-label="Tam eleme yapan takım" value={r.sweep??''} onChange={e=>setR({...r,sweep:e.target.value||null})}>{options}</select></label>{m.stage!=='group'&&r.a!==null&&r.a===r.b&&<label className="tie">Beraberlik: kazananı açıkça seçin<select aria-label="Beraberlik: kazananı açıkça seçin" value={r.winner??''} onChange={e=>setR({...r,winner:e.target.value||null})}>{options}</select><small>Kazanan seçilmeden sonraki tura takım aktarılmaz.</small></label>}<div className="modal-actions"><button type="button" onClick={()=>setR({a:null,b:null,flag:null,sweep:null,winner:null})}>Sonucu temizle</button><button type="button" onClick={onClose}>Vazgeç</button><button className="primary">Sonucu kaydet</button></div></form></div>;
}
function Gate() {
 const [allowed,setAllowed]=useState(!embedded),[error,setError]=useState('Admin oturumu doğrulanıyor…');
 useEffect(()=>{
   if(!embedded)return;
   const expired=()=>{setAllowed(false);setError('Admin oturumu sona erdi. Ana panelden yeniden giriş yapın.');};
   window.addEventListener('turnuva-auth-expired',expired);
   apiFetch('/api/tournaments').then(r=>{if(!r.ok)throw new Error('Admin oturumu doğrulanamadı. Ana panelden giriş yapın.');setAllowed(true);}).catch(e=>setError(e.message));
   return()=>window.removeEventListener('turnuva-auth-expired',expired);
 },[]);
 return allowed?<App/>:<div className="auth-message" role="alert">{error}</div>;
}
createRoot(document.getElementById('root')!).render(<Gate/>);
