(function(root) {
  const profiles = [{"id": "team_ghost", "name": "Şenol", "callsign": "Amca", "title": "Takim Lideri", "badge": "Lider", "photo": "https://images.unsplash.com/photo-1608064229007-dca149d32c4f?auto=format&fit=crop&w=900&q=80", "bio": "Senaryo tasarimi, saha koordinasyonu ve telsiz protokollerinden sorumlu.", "expertise": "DMR", "seasons": "5. sezon", "setup": "Hk416a5 - SSP18"}, {"id": "team_mamba", "name": "Gökberk", "callsign": "İmer", "title": "Safety Officer | Medic egitimi", "badge": "Safety", "photo": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=80", "bio": "Guvenlik brifingi, ilk yardim kiti ve saha ici risk kontrolunu yonetir.", "expertise": "Medic & Safety", "seasons": "5. sezon", "setup": "HK416a5 - SSP5"}, {"id": "team_ali_ihsan_yazarli", "name": "Ali İhsan Yazarlı", "callsign": "", "title": "Oyuncu", "badge": "Üye", "photo": "", "bio": "", "expertise": "", "seasons": "", "setup": ""}, {"id": "team_fethi_cem_gursu", "name": "Fethi Cem Gürsu", "callsign": "", "title": "Oyuncu", "badge": "Üye", "photo": "", "bio": "", "expertise": "", "seasons": "", "setup": ""}, {"id": "team_berkan_akyol", "name": "Berkan Akyol", "callsign": "", "title": "Oyuncu", "badge": "Üye", "photo": "", "bio": "", "expertise": "", "seasons": "", "setup": ""}, {"id": "team_nurullah_uckan", "name": "Nurullah Uçkan", "callsign": "", "title": "Oyuncu", "badge": "Üye", "photo": "", "bio": "", "expertise": "", "seasons": "", "setup": ""}, {"id": "team_hakan_ince", "name": "Hakan İnce", "callsign": "", "title": "Oyuncu", "badge": "Üye", "photo": "", "bio": "", "expertise": "", "seasons": "", "setup": ""}];
  const samples = [{"id": "team_forge", "name": "Emir", "callsign": "Forge", "title": "Ekipman mentoru", "badge": "Tech", "photo": "https://images.unsplash.com/photo-1545167622-3a6ac756afa4?auto=format&fit=crop&w=900&q=80", "bio": "Kronograf, bakim, yedek ekipman ve butce dostu setup onerileri sunar.", "expertise": "Tech & DMR", "seasons": "6. sezon", "setup": "DMR 1.64J"}, {"id": "team_spark", "name": "Deniz", "callsign": "Spark", "title": "Medya | After Action", "badge": "Media", "photo": "https://images.unsplash.com/photo-1522556189639-b150c3a2e10f?auto=format&fit=crop&w=900&q=80", "bio": "Oyun goruntuleri, highlight montajlari ve AAR notlarinin paylasimini yapar.", "expertise": "Recon & Media", "seasons": "3. sezon", "setup": "Carbine + action cam"}, {"id": "team_placeholder_5", "name": "Ad", "callsign": "Callsign", "title": "Rol - Guncelleniyor", "badge": "Member", "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80", "bio": "Oyuncu bilgileri yakin zamanda eklenecek.", "expertise": "-", "seasons": "-", "setup": "-"}, {"id": "team_placeholder_6", "name": "Ad", "callsign": "Callsign", "title": "Rol - Guncelleniyor", "badge": "Member", "photo": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80", "bio": "Oyuncu bilgileri yakin zamanda eklenecek.", "expertise": "-", "seasons": "-", "setup": "-"}, {"id": "team_placeholder_7", "name": "Ad", "callsign": "Callsign", "title": "Rol - Guncelleniyor", "badge": "Member", "photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80", "bio": "Oyuncu bilgileri yakin zamanda eklenecek.", "expertise": "-", "seasons": "-", "setup": "-"}, {"id": "team_placeholder_8", "name": "Ad", "callsign": "Callsign", "title": "Rol - Guncelleniyor", "badge": "Member", "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80", "bio": "Oyuncu bilgileri yakin zamanda eklenecek.", "expertise": "-", "seasons": "-", "setup": "-"}];
  function apply(current) {
    const result = (Array.isArray(current) ? current : []).filter(p => !samples.some(s => p.id === s.id && p.name === s.name && p.callsign === s.callsign));
    for (const player of profiles) {
      if (!result.some(p => p.id === player.id || p.name === player.name)) result.push({ ...player });
    }
    return result;
  }
  const api = { profiles, apply };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.RdatTeam = api;
}(typeof window === 'object' ? window : globalThis));
