import { describe,it,expect } from 'vitest';
import { fresh,draw,demo,stats,compare,standings,thirds,groupComplete,winner,loser,setResult,summary,validateTournament,emptyResult,type Match,type Tournament } from '../src/engine';
const base=()=>{const t=fresh();t.teams=Array.from({length:40},(_,i)=>({id:`t${i}`,name:`Takım ${i}`,city:'',captain:'',players:[]}));return draw(t,'42');};
const result=(a:number|null,b:number|null,flag:string|null=null,sweep:string|null=null,w:string|null=null)=>({a,b,flag,sweep,winner:w});
const match=(id:string,a:number|null,b:number|null,flag:string|null=null,sweep:string|null=null):Match=>({id,stage:'group',round:'Grup A',home:'a',away:'b',result:result(a,b,flag,sweep)});
describe('Excel puanlama ve sıralama',()=>{
 it('Galibiyet 3, beraberlik 1, bayrak 5, tam eleme 2; vurulan oyuncu toplamı',()=>{const s=stats(['a','b'],[match('1',3,1,'a','a'),match('2',2,2),match('3',null,9,'b','b')]);expect(s[0]).toMatchObject({played:2,points:11,hits:5,flags:1,sweeps:1});expect(s[1]).toMatchObject({played:2,points:1,hits:3,flags:0});});
 it('0–0 oynanmış, tek skor veya boş skor oynanmamış sayılır',()=>{expect(stats(['a'],[match('1',0,0),match('2',null,0),match('3',null,null)])[0]).toMatchObject({played:1,points:1,hits:0});});
 it('Her eşitlik ölçütü doğru sırada karşılaştırılır',()=>{const a=stats(['a'],[])[0];for(const k of ['points','hits','flags','sweeps'] as const){expect(compare({...a,[k]:2},{...a,[k]:1})).toBeLessThan(0);}expect(compare({...a,points:2,hits:0},{...a,points:1,hits:999})).toBeLessThan(0);});
 it('Tam eşitlik kura sırasını korur',()=>{const t=base();expect(standings(t).map(g=>g.map(s=>s.id))).toEqual(t.groups);});
 it('Seed deterministiktir, sıra bağımsızdır ve 60 benzersiz maç üretir',()=>{const t=base();const reversed={...t,teams:[...t.teams].reverse()};expect(draw(reversed,'42').groups).toEqual(t.groups);expect(draw(t,'43').groups).not.toEqual(t.groups);expect(t.matches.filter(m=>m.stage==='group')).toHaveLength(60);expect(new Set(t.groups.flat()).size).toBe(40);expect(draw(demo(),'2026').matches).toEqual(demo().matches);});
 it('Eksik takım ile kura reddedilir',()=>expect(()=>draw(fresh(),'1')).toThrow());
 it('Tüm üçüncüler eşitse A en iyi, J en başarısız ve sekiz farklı katılımcı',()=>{let t=base();for(const m of t.matches.filter(m=>m.stage==='group'))t=setResult(t,m.id,result(0,0)).tournament;expect(thirds(t).map(s=>s.group)).toEqual([0,1,2,3,4,5,6,7,8,9]);const ids=t.matches.filter(m=>m.id.startsWith('tq')).flatMap(m=>[m.home,m.away]);expect(new Set(ids).size).toBe(8);expect(ids).toEqual(standings(t).slice(1,9).map(g=>g[2].id));expect(t.matches.find(m=>m.id==='fp1')!.home).toBe(standings(t)[0][2].id);});
 it('59 maç tamamlanınca eleme katılımcıları kesinleşmez',()=>{let t=base();for(const m of t.matches.filter(m=>m.stage==='group').slice(0,59))t=setResult(t,m.id,result(2,1)).tournament;expect(groupComplete(t)).toBe(false);expect(t.matches.filter(m=>m.stage!=='group').every(m=>!m.home&&!m.away)).toBe(true);});
});
describe('Eleme ve düzeltme',()=>{
 it('Beraberlikte bayrak veya tam eleme tek başına kazanan değildir',()=>{const m={...match('1',2,2,'a','a'),stage:'finals' as const};expect(winner(m)).toBeNull();expect(winner({...m,result:result(2,2,'a','a','b')})).toBe('b');expect(loser({...m,result:result(2,2,null,null,'b')})).toBe('a');});
 it('Skor galibi, beraberlik seçimi ve geçersiz seçimin reddi',()=>{let t=demo();const m=t.matches.find(x=>x.id==='fp0')!;t=setResult(t,m.id,result(1,1,m.home,m.home)).tournament;expect(t.matches.find(x=>x.id==='fr2')!.away).toBeNull();t=setResult(t,m.id,result(1,1,null,null,m.away)).tournament;expect(t.matches.find(x=>x.id==='fr2')!.away).toBe(m.away);expect(()=>setResult(t,m.id,result(1,1,null,null,'bad'))).toThrow();expect(()=>setResult(t,m.id,result(2,1,null,null,m.home))).toThrow();});
 it('Her turun galibi doğru maçlara aktarılır; bronz önce görünür',()=>{const t=demo();const get=(id:string)=>t.matches.find(m=>m.id===id)!;for(let i=0;i<2;i++){expect(get(`ts${i}`).home).toBe(winner(get(`tq${i*2}`)));expect(get(`ts${i}`).away).toBe(winner(get(`tq${i*2+1}`)));expect(get(`fs${i}`).home).toBe(winner(get(`fq${i*2}`)));expect(get(`fs${i}`).away).toBe(winner(get(`fq${i*2+1}`)));}expect(get('tf').home).toBe(winner(get('ts0')));expect(get('tf').away).toBe(winner(get('ts1')));expect(get('fp5').home).toBe(winner(get('tf')));const ss=standings(t);const pre=[[ss[5][1].id,ss[1][1].id],[thirds(t)[0].id,ss[0][1].id],[ss[3][1].id,ss[7][1].id],[ss[2][1].id,ss[4][1].id],[ss[6][1].id,ss[9][1].id],[winner(get('tf')),ss[8][1].id]];pre.forEach((p,i)=>expect([get(`fp${i}`).home,get(`fp${i}`).away]).toEqual(p));const r16=[[ss[7][0].id,ss[8][0].id],[ss[1][0].id,winner(get('fp1'))],[ss[9][0].id,winner(get('fp0'))],[ss[6][0].id,winner(get('fp3'))],[winner(get('fp4')),ss[2][0].id],[ss[5][0].id,winner(get('fp5'))],[ss[4][0].id,ss[0][0].id],[winner(get('fp2')),ss[3][0].id]];r16.forEach((p,i)=>expect([get(`fr${i}`).home,get(`fr${i}`).away]).toEqual(p));for(let i=0;i<4;i++){expect(get(`fq${i}`).home).toBe(winner(get(`fr${i*2}`)));expect(get(`fq${i}`).away).toBe(winner(get(`fr${i*2+1}`)));}expect([get('fb').home,get('fb').away]).toEqual([loser(get('fs0')),loser(get('fs1'))]);expect([get('ff').home,get('ff').away]).toEqual([winner(get('fs0')),winner(get('fs1'))]);expect(t.matches.findIndex(m=>m.id==='fb')).toBeLessThan(t.matches.findIndex(m=>m.id==='ff'));});
 it('Önceki galip değişince etkilenen sonuçlar temizlenir, ilgisiz skor korunur',()=>{const t=demo();const changed=setResult(t,'fs0',result(1,5));expect(changed.invalidated).toEqual(['fb','ff']);for(const id of changed.invalidated)expect(changed.tournament.matches.find(m=>m.id===id)!.result).toEqual(emptyResult());expect(changed.tournament.matches.find(m=>m.id==='fs1')).toEqual(t.matches.find(m=>m.id==='fs1'));expect(summary(changed.tournament).gold).toBe('');expect(summary(changed.tournament).bronze).toBe('');});
 it('Galip aynıysa sonraki skor korunur; sonuç silinince zincir temizlenir',()=>{const t=demo();expect(setResult(t,'fs0',result(9,1)).invalidated).toEqual([]);const x=setResult(t,'tq0',emptyResult());expect(x.invalidated).toContain('ts0');expect(winner(x.tournament.matches.find(m=>m.id==='tf'))).toBeNull();});
 it('Grup sonucu değişince yeni katılımcılar türetilir ve eski skorlar silinir',()=>{const t=demo();const m=t.matches.find(x=>x.stage==='group')!;const x=setResult(t,m.id,result(0,999,m.away,m.away));expect(x.invalidated.length).toBeGreaterThan(0);validateTournament(x.tournament);});
 it('Negatif, kesirli, eksik ve maç dışı veri reddedilir',()=>{const t=demo();for(const r of [result(-1,2),result(1.5,2),result(1,2,'bad')])expect(()=>setResult(t,'fp0',r)).toThrow();const empty=base();expect(()=>setResult(empty,'fp0',result(2,1))).toThrow();});
});
describe('Özet ve uçtan uca demo',()=>{
 it('60 + 7 + 22 = 89 maç tamamlanır; üç farklı madalya ve tek bronz',()=>{const t=demo();validateTournament(t);expect(t.matches).toHaveLength(89);expect(t.matches.filter(m=>m.stage==='group')).toHaveLength(60);expect(t.matches.filter(m=>m.stage==='third')).toHaveLength(7);expect(t.matches.filter(m=>m.stage==='finals')).toHaveLength(22);expect(t.matches.every(m=>m.stage==='group'?m.result.a!==null:!!winner(m))).toBe(true);const s=summary(t);expect(new Set([s.gold,s.silver,s.bronze]).size).toBe(3);expect(s.bronze).not.toContain(' - ');expect(s.gold).toBe(t.teams.find(x=>x.id===winner(t.matches.find(m=>m.id==='ff')))?.name);expect(s.silver).toBe(t.teams.find(x=>x.id===loser(t.matches.find(m=>m.id==='ff')))?.name);});
 it('Eşit istatistik liderleri birlikte yazılır; sıfır değer boş kalır',()=>{let t=base();const m=t.matches.find(x=>x.stage==='group')!;t=setResult(t,m.id,result(2,2)).tournament;const names=[m.home,m.away].map(id=>t.teams.find(x=>x.id===id)!.name);const s=summary(t);expect(s.group.points.split(' - ').sort()).toEqual(names.sort());expect(s.group.hits.split(' - ').sort()).toEqual(names.sort());expect(s.group.flags).toBe('');expect(s.finals.points).toBe('');});
 it('Finaller istatistiklerinde üçüncüler sayılmaz ve bonuslar hesaplanır',()=>{const t=demo();const values=stats(t.teams.map(x=>x.id),t.matches.filter(m=>m.stage==='finals'));const s=summary(t);for(const k of ['points','hits','flags','sweeps'] as const){const max=Math.max(...values.map(x=>x[k]));const expected=max?values.filter(x=>x[k]===max).map(x=>t.teams.find(team=>team.id===x.id)!.name).join(' - '):'';expect(s.finals[k]).toBe(expected);}});
 it('Kaydet/aç JSON döngüsü aynı sonuçları korur',()=>{const t=demo();const copy=JSON.parse(JSON.stringify(t));validateTournament(copy);expect(summary(copy)).toEqual(summary(t));expect(copy.matches).toEqual(t.matches);});
 it('Tekrarlı takım ve bozuk grup dosyaları reddedilir',()=>{const t=demo();t.teams[1].name=t.teams[0].name;expect(()=>validateTournament(t)).toThrow();const x=demo();x.groups[0][0]=x.groups[0][1];expect(()=>validateTournament(x)).toThrow();});
});
